using System;
using System.Collections.Generic;

namespace myLabWebApi.Models.New
{
    public partial class QER_TESTS
    {
        public int TESTMST_CurrentId { get; set; }
        public string TESTMST_Name { get; set; }
        public string TESTMST_PrintFormat { get; set; }
        public double? TESTMST_Rate { get; set; }
        public string TESTMST_ReportHeading { get; set; }
        public string Type { get; set; }
        public double? TESTMST_Testcost { get; set; }
        public string TESTMST_Alias { get; set; }
        public double? TESTMST_Percentage { get; set; }
        public double? TESTMST_Lumsum { get; set; }
        public string Active { get; set; }
        public string Comments { get; set; }
        public int? TESTMST_Companyid { get; set; }
        public int? TESTMST_TestTypeId { get; set; }
        public string TESTMST_CatType { get; set; }
        public string SpecialTest { get; set; }
        public string PATIENT_Name { get; set; }
        public string PATIENT_Address1 { get; set; }
        public string PATIENT_Address2 { get; set; }
        public string PATIENT_City { get; set; }
        public string PATIENT_State { get; set; }
        public string PATIENT_Region { get; set; }
        public long PATIENT_Country { get; set; }
        public string PATIENT_Pincode { get; set; }
        public string PATIENT_Telno { get; set; }
        public string PATIENT_Gender { get; set; }
        public string PATIENT_Age { get; set; }
        public DateTime? PATIENT_Date { get; set; }
        public double? PATIENT_AmountPaid { get; set; }
        public int? PATIENT_SampleCollected { get; set; }
        public double? TotalAmount { get; set; }
        public double? EmergencyCharges { get; set; }
        public double? PATIENT_Discount { get; set; }
        public double? EmergencyChargesPecent { get; set; }
        public string Remarks { get; set; }
        public int? Patientno { get; set; }
        public int DOCHDR_lDocumentId { get; set; }
        public string DOCHDR_sDocNo { get; set; }
        public long? DOCHDR_lPatientId { get; set; }
        public int? DOCHDR_lDoctorId { get; set; }
        public string DOCHDR_sDescription { get; set; }
        public DateTime? DOCHDR_dDate { get; set; }
        public int? DOCHDR_TestCatID { get; set; }
        public string DOCHDR_Sex { get; set; }
        public string DOCHDR_Age { get; set; }
        public int? DOCHDR_Sample { get; set; }
        public double? DOCHDR_Rate { get; set; }
        public bool DOCHDR_bCommission { get; set; }
        public int? DOCHDR_lEmployeeId { get; set; }
        public short? NoOfPrintOuts { get; set; }
        public string MarkComplete { get; set; }
        public int? Doctorid2 { get; set; }
        public int? labno { get; set; }
        public string WardNo { get; set; }
        public string HOSPTYPE { get; set; }
        public DateTime? Sample_Date { get; set; }
        public string userid { get; set; }
        public DateTime? Currentdate { get; set; }
        public int? ProfileId { get; set; }
        public string IsProfile { get; set; }
        public string DOCHDR_AgeFlag { get; set; }
        public int DOCDET_lHeaderId { get; set; }
        public int DOCDET_lFieldNo { get; set; }
        public string DOCDET_tFieldValue { get; set; }
        public int? DOCDET_lTestCatId { get; set; }
        public string DOCDET_tFieldValue1 { get; set; }
        public int? DOCTOR_id { get; set; }
        public string DOCTOR_Name { get; set; }
        public string DOCTOR_Address1 { get; set; }
        public string DOCTOR_Address2 { get; set; }
        public string DOCTOR_City { get; set; }
        public string DOCTOR_State { get; set; }
        public string DOCTOR_Region { get; set; }
        public string DOCTOR_Country { get; set; }
        public string DOCTOR_Pincode { get; set; }
        public string DOCTOR_Telno { get; set; }
        public string DOCTOR_MobileNo { get; set; }
        public string DOCTOR_Email { get; set; }
        public string DOCTOR_Qualification { get; set; }
        public string OFFICE_Address1 { get; set; }
        public string OFFICE_Address2 { get; set; }
        public string OFFICE_City { get; set; }
        public string OFFICE_State { get; set; }
        public string OFFICE_Region { get; set; }
        public string OFFICE_Country { get; set; }
        public string OFFICE_Pincode { get; set; }
        public string OFFICE_Telno { get; set; }
        public string OFFICE_url { get; set; }
        public double? DOCTOR_Commission { get; set; }
        public int? DOCTOR_Companyid { get; set; }
        public string DOCTOR_Permanent { get; set; }
        public double? DOCTOR_XCommission { get; set; }
        public int? DOCTOR_SCommission { get; set; }
        public double? DOCTOR_RCommission { get; set; }
        public double? DOCTOR_PFCommission { get; set; }
        public double? DOCTOR_SPCommission { get; set; }
        public double? DOCTOR_MCommission { get; set; }
        public double? DOCTOR_OCommission { get; set; }
        public double? DOCTOR_HCommission { get; set; }
        public double? DOCTOR_EXCommission { get; set; }
        public double? DOCTOR_EX1Commission { get; set; }
        public string EMPLOYEE_Name { get; set; }
        public string DOC2 { get; set; }
        public string CENTER_Name { get; set; }
        public string docq2 { get; set; }
        public byte[] WBC { get; set; }
        public byte[] RBC { get; set; }
        public byte[] PLT { get; set; }
        public string PATIENT_AgeFlag { get; set; }
        public int TESTDET_CurrentId { get; set; }
        public int? TESTDET_TestMasterID { get; set; }
        public int? TESTDET_FieldNo { get; set; }
        public string TESTDET_FieldName { get; set; }
        public short? TESTDET_FieldType { get; set; }
        public string TESTDET_NormalValue { get; set; }
        public double? TESTDET_MinValue { get; set; }
        public double? TESTDET_MaxValue { get; set; }
        public string TESTDET_Description { get; set; }
        public string TESTDET_GroupName { get; set; }
        public int? TESTDET_GroupNo { get; set; }
        public short? TESTDET_FieldStyle { get; set; }
        public bool? TESTDET_Compulsory { get; set; }
        public string TESTDET_sDefault { get; set; }
        public string TESTDET_sAlias { get; set; }
        public string TESTDET_sUnit { get; set; }
        public string TESTDET_sFormula { get; set; }
        public double? TESTDET_MaxLimit { get; set; }
        public double? TESTDET_MinLimit { get; set; }
        public bool? TESTDET_Validate { get; set; }
        public string ProfileName { get; set; }
        public string TESTMST_sample { get; set; }
        public string UrgentFlag { get; set; }
        public string BalanceFlag { get; set; }
        public DateTime? RegistationDate { get; set; }
        public string RegistationUser { get; set; }
        public DateTime? SampleReceivedDate { get; set; }
        public string SampleReceivedUser { get; set; }
        public DateTime? DataEntryDate { get; set; }
        public string DataEntryUser { get; set; }
        public DateTime? ValidateDate { get; set; }
        public string ValidateUser { get; set; }
        public DateTime? ResampleDate { get; set; }
        public string ResampleUser { get; set; }
        public DateTime? RerunDate { get; set; }
        public string RerunUser { get; set; }
        public DateTime? AuntheticateDate { get; set; }
        public string AuthenticateUser { get; set; }
        public DateTime? PrintDate { get; set; }
        public string PrintUser { get; set; }
        public DateTime? PDFDate { get; set; }
        public string PDFUser { get; set; }
        public DateTime? EmailDate { get; set; }
        public string EmailUser { get; set; }
        public string SampleReceivedRemark { get; set; }
        public string Lable_Sample { get; set; }
        public DateTime? RequestDate { get; set; }
        public string RequestUser { get; set; }
        public DateTime? IntegrationDate { get; set; }
        public int? TAT { get; set; }
        public string IsNABL { get; set; }
    }
}
